export default function getAllPosts() {

  var colors = [
    '#FCF8A8',
    '#D4FF9E',
    '#FFC6C9',
    '#FBE3FF',
    '#E3EEFF',
    '#FFE9F6',
    '#FFFFFF',
  ]

  const randomColor = (colors: Array<string>) => {
    return colors[Math.floor(Math.random() * colors.length)];
  }


  let id = 10;
  let items = [
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    }, {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    }, {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
    {
      text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit nulla ipsa molestiae laborum, quibusdam esse ea placeat nostrum.",
      id: id = id + 1,
      favorites: 100,
      color: randomColor(colors),
    },
  ];

  return items;
}